name: Generate Cordova APK
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.4.0'
    - name: Install Quasar
      run: npm install -g @quasar/cli
    - name: Quasar Version
      run: quasar -v
    - name: Install Cordova
      run: npm install -g cordova
    - name: Cordova Version
      run: cordova -v
    - name: Quasar Build for Cordova
      run: quasar build -m cordova -T android
    - name: Build Cordova
      run: |
        cordova platform remove android
        cordova platform add android
        cordova build android
      working-directory: ./src-cordova
    
