name: Generate Cordova APK
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: 'Create a file'
      run: echo ${{ github.workspace }}/src-cordova/platforms/android/app/build/outputs/apk/debug/ > app-debug.txt
    - name: 'Move to directory'
      run: |
        mkdir -p output
        yes| cp -rf ${{ github.workspace }}/src-cordova/platforms/android/app/build/outputs/apk/debug/app-debug.txt ./output/
    - name: Commit files # commit the output folder
      run: |
        git config --local user.email "test@github.com"
        git config --local user.name "GitHub Action test"
        git add ./output
        git commit -m "Add changes"
    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
      
